server:
  port: 8010

#acutator 服务监控
management:
  endpoint:
      health:
        show-details: always
  endpoints:
    web:
      exposure:
        include: '*'

#eureka服务注册
spring:
  application:
      # 指定注册到eureka server上的服务名称，对于电影微服务，本系列将名称设为microservice-consumer-movie
      name: microservice-simple-consumer-movie-feign-hystrix-common
  eureka:
    client:
      service-url:
        # 指定eureka server通信地址，注意/eureka/小尾巴不能少
        defaultZone: http://localhost:8761/eureka/
    instance:
      # 是否注册IP到eureka server，如不指定或设为false，那就会注册主机名到eureka server
      prefer-ip-address: true

#全局启用hystrix
feign:
  hystrix:
    enabled: true

turbine:
  # 要监控的微服务列表，多个用,分隔
  appConfig: microservice-simple-consumer-movie-feign-hystrix-common
  clusterNameExpression: "'default'"